// import all css files 
import(/* webpackPreload: true */ './../css/fonts.css');
import(/* webpackPreload: true */ './../css/style.css');
import(/* webpackPreload: true */ './../css/datawindow.css');
import(/* webpackPreload: true */ './../css/components/hbbtn.css');
import(/* webpackPreload: true */ './../css/components/minput.css');
import(/* webpackPreload: true */ './../css/components/socialbtn.css');
import(/* webpackPreload: true */ './../css/components/slidebtn.css');
import(/* webpackPreload: true */ './../css/components/tabsv.css');